apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # namespace: testcluster
  labels:
    pg-cluster: crdcluster
type: Opaque
data:
  POSTGRES_USER: dXNlcjAxCg==   # user01
  POSTGRES_PASSWORD: cGFzc3dvcmQK   # password
# stringData:   # 쓰기 전용
#   foo: plain text  