apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  # namespace: testcluster
  labels:
    pg-cluster: crdcluster
type: Opaque
# data:
#   POSTGRES_USER: dXNlcjAxCg==   # user01
#   POSTGRES_PASSWORD: cGFzc3dvcmQK   # password
#   POSTGRES_DB: dGVzdGRiCg==   # testdb
stringData:
  POSTGRES_USER: user01
  POSTGRES_PASSWORD: password
  POSTGRES_DB: testdb