apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis-dev
  ports: 
  - name: redis-port
    port: 6379
    nodePort: 30379
    targetPort: redis-port
    protocol: TCP
