apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis-dev
spec:
  containers:
  - name: redis
    image: redis:6.2.13
    ports:
    - name: redis-port
      containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
