apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: devsample
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin1234
        - name: MARIADB_ROOT_PASSWORD
          value: admin1234
